#include "Timer.h"


void Timer_Init(void)
{
	#ifdef INPUT_EGDE_TIME_INT_MODE
		SET_BIT(REG(Timer0_16_32_base,RCGCTIMER),TIMER0);
		CLEAR_BIT(REG(Timer0_16_32_base,GPTMCTL),TAEN);
		REG(Timer0_16_32_base,GPTMCFG) = HALF_MODE;
		SET_BIT_VALUE(REG(Timer0_16_32_base,GPTMTAMR),TACMR,EDGE_TIME);
		SET_BIT_VALUE(REG(Timer0_16_32_base,GPTMTAMR),TAMR,CAPTURE);
		SET_BIT_VALUE(REG(Timer0_16_32_base,GPTMCTL),TAEVENT,BOTH_EDGES);
		SET_BIT_VALUE(REG(Timer0_16_32_base,GPTMTAMR),TACDIR,UP);
		REG(Timer0_16_32_base,GPTMTAPR) = 0xFF;
		REG(Timer0_16_32_base,GPTMTAILR) = 0xFFFF;
	#endif
}

